### PR TITLE
new Update new.py

### PR DESCRIPTION
**Pull request by fernandezbaptiste**

### CODE REVIEW

**Comment by fernandezbaptiste** [comment]
@quest-bot loot #9

**Comment by laucharles98** [comment]
@quest-bot loot #9

**Comment by fernandezbaptiste** [comment]
@quest-bot restash 123

**Comment by fernandezbaptiste** [comment]
@quest-bot stash 123

**Comment by fernandezbaptiste** [comment]
@quest-bot embark

**Comment by quinehp1119** [comment]
@quest-bot abort

**Comment by quinehp1119** [comment]
@quest-bot abort #9

**Comment by quinehp1119** [comment]
@quest-bot reward @fernandezbaptiste

**Comment by quinehp1119** [comment]
@quest-bot restash 1234

**Comment by quinehp1119** [comment]
@quest-bot stash 1234

**Pull request closed without merging**
